
On illumos, sendfile(fd1, fd1) succeeds without raising an exception

diff --git a/Lib/test/test_shutil.py b/Lib/test/test_shutil.py
index 7669b94..eb933ce 100644
--- a/Lib/test/test_shutil.py
+++ b/Lib/test/test_shutil.py
@@ -2392,7 +2392,7 @@ class _ZeroCopyFileTest(object):
     def test_same_file(self):
         self.addCleanup(self.reset)
         with self.get_files() as (src, dst):
-            with self.assertRaises(Exception):
+            #with self.assertRaises(Exception):
                 self.zerocopy_fun(src, src)
         # Make sure src file is not corrupted.
         self.assertEqual(read_file(TESTFN, binary=True), self.FILEDATA)
